Added plugs `home` & `unity7`
NickvisionApps/TubeConverter pull request #235
Opened 2023-05-07 17:16 UTC by soumyaDghosh

2023-05-07 17:52 UTC, soumyaDghosh commented
Seems like the snap is crashing, I don't know why and how

2023-05-07 18:42 UTC, nlogozzo commented
No error messages?

2023-05-07 18:49 UTC, fsobolev commented
home plug isn't needed since #223

2023-05-07 19:15 UTC, nlogozzo requested changes

2023-05-07 19:15 UTC, nlogozzo commented on snap/snapcraft.yaml
> +      - home
Not needed

2023-05-08 21:27 UTC, nlogozzo approved these changes

2023-05-08 21:27 UTC, merged